name: Build firmware images
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency:
  group: ci-firmware-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  firmware:
    runs-on: cncf-ubuntu-32-128-x86
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Log in to the Container registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build firmware
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./firmware.sh --build
      - name: Publish firmware on tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./firmware.sh --build --push --repository ghcr.io/${{ github.repository }} --firmware-version ${{ github.ref_name }}
      - name: Build sysexts on tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./firmware.sh --repository ghcr.io/${{ github.repository }} --sysext
          mv build unsigned-sysext
      - name: Build sysexts
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./firmware.sh --sysext
          mv build unsigned-sysext
      - name: Build signed sysext
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./firmware.sh --sysext --private-key .github/keys/PK.key --certificate .github/keys/PK.pem
          mv build signed-sysext
      - name: Upload sysext artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v7
        with:
          name: unsigned-sysext
          path: unsigned-sysext/
      - name: Upload signed sysext artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v7
        with:
            name: signed-sysext
            path: signed-sysext/
      - name: Release sysexts on tag
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            unsigned-sysext/*
